const express = require('express');
const router = express.Router();

const availabilityRouter = require('../routes/availabilityRouter');
const ayacutnoncultivationRouter = require('../routes/ayacutnoncultivationRouter');
const boundaryDropPointsRouter = require('../routes/boundaryDropPointsRouter');
const bundIssueRouter = require('../routes/bundIssueRouter');
const barrelTypeRouter = require('../routes/barrelTypeRouter');
const bundRouter = require('../routes/bundRouter');
const conditionRouter = require('../routes/conditionRouter');
const catchmentTypeRouter = require('../routes/catchmentTypeRouter');
const croppingRouter = require('../routes/croppingRouter');
const crossSectionRouter = require('../routes/crossSectionRouter');
const damStoneRouter = require('../routes/damStoneRouter');
const distributionLandRouter = require('../routes/distributionLandRouter');
const depthSillLevelRouter = require('../routes/depthSillLevelRouter');
const exoticSpeciesRouter = require('../routes/exoticSpeciesRouter');
const familyNatureRouter = require('../routes/familyNatureRouter');
const fieldChannelTypeRouter = require('../routes/fieldChannelTypeRouter');
const fenceConditionRouter = require('../routes/fenceConditionRouter');
const fenceTypeRouter = require('../routes/fenceTypeRouter');
const ghatConditionRouter = require('../routes/ghatConditionRouter');
const inletTypeRouter = require('../routes/inletTypeRouter');
const natureInvestmentRouter = require('../routes/natureInvestmentRouter');
const ownershipRouter = require('../routes/ownershipRouter');
const outletTypeRouter = require('../routes/outletTypeRouter');
const ooraniFunctionRouter = require('../routes/ooraniFunctionRouter');
const mwlStonesRouter = require('../routes/mwlStonesRouter');
const pitchingConditionRouter = require('../routes/pitchingConditionRouter');
const sourceRouter = require('../routes/sourceRouter');
const spreadIssueRouter = require('../routes/spreadIssueRouter');
const sluicesSurplusTypeRouter = require('../routes/sluicesSurplusTypeRouter');
const surplusWeirRouter = require('../routes/surplusWeirRouter');
const slitTrapRouter = require('../routes/slitTrapRouter');
const streamIssueRouter = require('../routes/streamIssueRouter');
const shutterRouter = require('../routes/shutterRouter');
const shutterConditionRouter = require('../routes/shutterConditionRouter');
const stonePitchingRouter = require('../routes/stonePitchingRouter');
const typeRouter = require('../routes/typeRouter');
const tankFunctionRouter = require('../routes/tankFunctionRouter');
const tankTypeRouter = require('../routes/tankTypeRouter');
const tankUniquenessRouter = require('../routes/tankUniquenessRouter');
const templeTankTypeRouter = require('../routes/templeTankTypeRouter');
const tankIssueRouter = require('../routes/tankIssueRouter');
const freeCatchmentRouter = require('../routes/freeCatchmentRouter');
const waterSpreadAreaRouter = require('../routes/waterSpreadAreaRouter');
const surplusWeirsParameterRouter = require('../routes/surplusWeirsParameterRouter');
const invasiveSpeciesRouter = require('../routes/invasiveSpeciesRouter/index');
const retainingWallsRouter = require('../routes/retainingWallsRouter');
const retainingWallConditionRouter = require('../routes/retainingWallConditionRouter');
const encroachmentDetailsRouter = require('../routes/encroachmentDetailsRouter');
const surplusIssuesRouter = require('../routes/surplusIssuesRouter');
const encroachersLivingStandardRouter = require('../routes/encroachersLivingStandardRouter');
const encroachersAlternativeHousingRouter = require('../routes/encroachersAlternativeHousingRouter');
const boundaryStoneRouter = require('../routes/boundaryStoneRouter');
const activitiesUndertakenRouter = require('../routes/activitiesUndertakenRouter');
const natureOfBedsRouter = require('../routes/natureOfBedsRouter');
const natureOfEmbankmentRouter = require('../routes/natureOfEmbankmentRouter');
const currentStatusRouter = require('../routes/currentStatusRouter');
const wallDamageDirectionRouter = require('../routes/wallDamageDirectionRouter');
const natureOfEnchroachmentRouter = require('../routes/natureOfEnchroachmentRouter');
const statusOfEvictionRouter = require('../routes/statusOfEvictionRouter');
const monthRoutes = require('../routes/monthRouter/index');
const pastSourcesSupplyRoutes = require('../routes/pastSourcesSupplyRouter');
const natureWalkingPavementRoutes = require('../routes/natureWalkingPavementRouter');
const walkingPavementConditionRoutes = require('../routes/walkingPavementConditionRouter');
const fenceRoutes = require('../routes/fenceRouter');
const recreationalAreaConditionRouter = require('../routes/recreationalAreaConditionRouter');
const channelTypeRouter = require('../routes/channelTypeRouter');
const canalTypeRouter = require('../routes/canalTypeRouter');
const canalSystemNameRouter = require('../routes/canalSystemNameRouter');
const canalCrossSectionRouter = require('../routes/canalCrossSectionRouter');
const channelSourcesSupplyRouter = require('../routes/channelSourcesSupplyRouter');
const canalIssuesRouter = require('../routes/canalIssuesRouter');
const damConditionRouter = require('../routes/damConditionRouter');
const channelActivitiesUndertakenRouter = require('../routes/channelActivitiesUndertakenRouter');
const channelIssuesStreamRouter = require('../routes/channelIssuesStreamRouter');
const riverIssuesStreamRouter = require('../routes/riverIssuesStreamRouter');
const surplusUpperTankIssuesStreamRouter = require('../routes/surplusUpperTankIssuesStreamRouter');
const ooraniBundIssuesRouter = require('../routes/ooraniBundIssuesRouter');
const evictionSurplusCourseStatusRouter = require('../routes/evictionSurplusCourseStatusRouter');
const templeTankSourceSupplyRouter = require('../routes/templeTankSourceSupplyRouter');
const freeCatchmentStreamIssueRouter = require('../routes/freeCatchmentStreamIssueRouter');

router.use('/availability', availabilityRouter);
router.use('/ayacutnoncultivation', ayacutnoncultivationRouter);
router.use('/boundary-drop-point', boundaryDropPointsRouter);
router.use('/bund-issue', bundIssueRouter);
router.use('/barrel-type', barrelTypeRouter);
router.use('/bund', bundRouter);
router.use('/condition', conditionRouter);
router.use('/catchment-type', catchmentTypeRouter);
router.use('/cropping', croppingRouter);
router.use('/cross-section', crossSectionRouter);
router.use('/dam-stone', damStoneRouter);
router.use('/distribution-land', distributionLandRouter);
router.use('/depth-sill-level', depthSillLevelRouter);
router.use('/exotic-species', exoticSpeciesRouter);
router.use('/family-nature', familyNatureRouter);
router.use('/field-channel-type', fieldChannelTypeRouter);
router.use('/fence-condition', fenceConditionRouter);
router.use('/fence-type', fenceTypeRouter);
router.use('/ghat-condition', ghatConditionRouter);
router.use('/inlet-type', inletTypeRouter);
router.use('/nature-investment', natureInvestmentRouter);
router.use('/ownership', ownershipRouter);
router.use('/outlet-type', outletTypeRouter);
router.use('/oorani-function', ooraniFunctionRouter);
router.use('/mwl-stones', mwlStonesRouter);
router.use('/pitching-condition', pitchingConditionRouter);
router.use('/source', sourceRouter);
router.use('/spread-issue', spreadIssueRouter);
router.use('/sluices-surplus-type', sluicesSurplusTypeRouter);
router.use('/surplus-weir', surplusWeirRouter);
router.use('/slit-trap', slitTrapRouter);
router.use('/stream-issue', streamIssueRouter);
router.use('/shutter', shutterRouter);
router.use('/shutter-condition', shutterConditionRouter);
router.use('/stone-pitching', stonePitchingRouter);
router.use('/type', typeRouter);
router.use('/tank-function', tankFunctionRouter);
router.use('/tank-type', tankTypeRouter);
router.use('/tank-uniqueness', tankUniquenessRouter);
router.use('/temple-tank-type', templeTankTypeRouter);
router.use('/tank-issue', tankIssueRouter);
router.use('/free-catchment', freeCatchmentRouter);
router.use('/water-spread-area', waterSpreadAreaRouter);
router.use('/surplus-weir-parameter', surplusWeirsParameterRouter);
router.use('/invasive-species', invasiveSpeciesRouter);
router.use('/retaining-walls', retainingWallsRouter);
router.use('/retaining-wall-condition', retainingWallConditionRouter);
router.use('/encroachment-details', encroachmentDetailsRouter);
router.use('/surplus-issues', surplusIssuesRouter);
router.use('/encroachers-living-standard', encroachersLivingStandardRouter);
router.use('/encroachers-alternative-housing', encroachersAlternativeHousingRouter);
router.use('/boundary-stone', boundaryStoneRouter);
router.use('/activities-undertaken', activitiesUndertakenRouter);
router.use('/nature-of-beds', natureOfBedsRouter);
router.use('/nature-of-embankment', natureOfEmbankmentRouter);
router.use('/current-status', currentStatusRouter);
router.use('/wall-damage-directions', wallDamageDirectionRouter);
router.use('/nature-of-enchroachment', natureOfEnchroachmentRouter);
router.use('/status-of-eviction', statusOfEvictionRouter);
router.use('/months', monthRoutes);
router.use('/past-sources-supply', pastSourcesSupplyRoutes);
router.use('/nature-walking-pavement', natureWalkingPavementRoutes);
router.use('/walking-pavement-conditions', walkingPavementConditionRoutes);
router.use('/fence', fenceRoutes);
router.use('/recreational-area-condition', recreationalAreaConditionRouter);
router.use('/channel-types', channelTypeRouter);
router.use('/canal-types', canalTypeRouter);
router.use('/canal-system-names', canalSystemNameRouter);
router.use('/canal-cross-section', canalCrossSectionRouter);
router.use('/channel-sources-supply', channelSourcesSupplyRouter);
router.use('/canal-issues', canalIssuesRouter);
router.use('/dam-conditions', damConditionRouter);
router.use('/channel-activities-undertaken', channelActivitiesUndertakenRouter);
router.use('/channel-issues-stream', channelIssuesStreamRouter);
router.use('/river-issues-stream', riverIssuesStreamRouter);
router.use('/surplus-upper-tank-issues-stream', surplusUpperTankIssuesStreamRouter);
router.use('/oorani-bund-issues', ooraniBundIssuesRouter);
router.use('/eviction-surplus-course-status', evictionSurplusCourseStatusRouter);
router.use('/temple-tank-source-supply', templeTankSourceSupplyRouter);
router.use('/freecatchment-stream-issues', freeCatchmentStreamIssueRouter);

module.exports = router;